### ISSUE TITLE
books endpoint integration tests

### ISSUE THREAD

**Issue by mothmane** [hamzachikar/book-store#2]
Using SpringBootTest, we should provide integration tests for 

POST /books
PUT / books/
GET /books
GET /books/{id}
DELETE /books/{id}

**Comment by hamzachikar** [comment]
i have added tests for each endpoint request : 
    - sould_create_a_book
    - should_update_a_book
    - should_return_list_of_books
    - should_return_a_book_by_id
    - should_delete_a_book_by_id
